name: RepairPlus
main: RepairPlus\RepairPlus\Main
version: 1.0.0
api: [3.0.0, 3.8.3]
load: POSTWORLD
author: jhampt
commands:
 repair:
  alias: [fix]
  description: Repair Command
  usage: /repair
  permission: repair.command
permissions:
 repair.command:
  default: op
